version: '3.8'

services:
  backend:
    build: ./game-backend-new
    ports:
      - "8000:8000"
    volumes:
      - ./game-backend-new:/app
    environment:
      - PYTHONUNBUFFERED=1 # Ensures Python output is not buffered
      # IMPORTANT: This is a default secret key for development.
      # For a production environment, you should use a more secure, managed secret.
      # Generate a new one with: openssl rand -hex 32
      - SECRET_KEY=aef285d4bb501a6d826177b52a4d7dc2ec3a7e864a31b499045c27cdbd6d4ee7
      - FRONTEND_URL=http://localhost:3000
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # Use this for development with hot-reloading
    command: uvicorn main:app --host 0.0.0.0 --port 8000 # Use this for production

  frontend:
    build: ./game-frontend-new
    ports:
      - "3000:3000"
    volumes:
      - ./game-frontend-new:/app
      - /app/node_modules # Exclude node_modules from host bind mount
    depends_on:
      - backend # Ensure backend starts before frontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000 # Use service name for internal Docker communication
