name: terroir-and-time
services:
- name: frontend
  dockerfile_path: game-frontend-new/Dockerfile
  source_dir: game-frontend-new
  github:
    repo: https://github.com/placeholder-username/placeholder-repo-name
    branch: main
  routes:
  - path: /
  envs:
  - key: NEXT_PUBLIC_BACKEND_URL
    value: ${backend.INTERNAL_URL}
- name: backend
  dockerfile_path: game-backend-new/Dockerfile
  source_dir: game-backend-new
  github:
    repo: https://github.com/placeholder-username/placeholder-repo-name
    branch: main
  routes:
  - path: /api
