name: terroir-and-time
services:
- name: frontend
  dockerfile_path: game-frontend-new/Dockerfile
  source_dir: game-frontend-new
  github:
    repo: https://github.com/kennethkcox/winer-0.1
    branch: feat/docker-improvements
  routes:
  - path: /
  envs:
  - key: NEXT_PUBLIC_BACKEND_URL
    value: ${backend.INTERNAL_URL}
- name: backend
  dockerfile_path: game-backend-new/Dockerfile
  source_dir: game-backend-new
  github:
    repo: https://github.com/kennethkcox/winer-0.1
    branch: feat/docker-improvements
  routes:
  - path: /api
